[project]
name = "detray_sympy"
version = "0.1.0"
description = "Sympy-based code generator for detray"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.2",
    "sympy>=1.14.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
