# Detray library, part of the ACTS project (R&D line)
#
# (c) 2021-2024 CERN for the benefit of the ACTS project
#
# Mozilla Public License Version 2.0

stages:
  - build

build_cuda:
  tags: [docker]
  stage: build
  image: ghcr.io/acts-project/ubuntu2204_cuda:56
  script:
      - git clone https://gitlab.cern.ch/beyeo/continuous_benchmark
      - cd ./continuous_benchmark
      - echo "Hello World!" >> hello.txt
      - git config --global user.email "beomki.yeo@gmail.com"
      - git config --global user.name "Beomki Yeo"
      - git add hello.txt
      - git commit -m "Test"
      - git push -u origin master
