# Detray library, part of the ACTS project (R&D line)
#
# (c) 2021-2024 CERN for the benefit of the ACTS project
#
# Mozilla Public License Version 2.0

stages:
  - build
  - test

build_cuda:
  tags: [docker]
  stage: build
  image: ghcr.io/acts-project/ubuntu2204_cuda:56
  artifacts:
    paths:
      - build
  script:
      - echo "Hello, World!" > hello.txt
  cache:
    - key: cache-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - cache-$CI_DEFAULT_BRANCH
        - cache-default
      paths:
        - hello.txt
