stages:
  - build
  - test


build_cuda:
  tags: [docker]
  stage: build
  image: ghcr.io/acts-project/ubuntu2004_cuda:v30
  artifacts:
    paths:
      - build
  script:
      - git clone $CLONE_URL src
      - git -C src checkout $HEAD_SHA
      - >
        cmake -S src -B build 
        -DCMAKE_BUILD_TYPE=Release
        -DDETRAY_CUSTOM_SCALARTYPE=float
        -DBUILD_TESTING=ON
        -DDETRAY_BUILD_TESTING=ON
        -DDETRAY_BUILD_CUDA=ON
        -DDETRAY_VC_PLUGIN=OFF
        -DDETRAY_SMATRIX_PLUGIN=OFF
        -DDETRAY_EIGEN_PLUGIN=ON
      - cmake --build build


test_cuda:
  variables:
    DETRAY_DATA_DIRECTORY: src/data/
    DETRAY_BFIELD_FILE: $CI_PROJECT_DIR/src/data/odd-bfield_v0_9_0.cvf
  stage: test
  tags: [docker-gpu-nvidia]
  image: ghcr.io/acts-project/ubuntu2004_cuda:v30
  needs:
    - build_cuda
  script:
    - git clone $CLONE_URL src
    - git -C src checkout $HEAD_SHA
    - src/data/detray_data_get_files.sh
    - cd build
    - nvidia-smi
    - ctest --output-on-failure -R ".*cuda.*"
    - find bin -type f -name "*cuda" -not -name "*text*" -exec {} \;


build_sycl:
  tags: [docker]
  stage: build
  image: "ghcr.io/acts-project/ubuntu2004_oneapi:v30"
  artifacts:
    paths:
      - build
  script:
      - git clone $CLONE_URL src
      - git -C src checkout $HEAD_SHA
      - source src/.github/ci_setup.sh SYCL
      - >
        cmake -S src -B build 
        -DCMAKE_BUILD_TYPE=Release
        -DDETRAY_CUSTOM_SCALARTYPE=float
        -DDETRAY_BUILD_CUDA=OFF
        -DDETRAY_BUILD_SYCL=ON
        -DBUILD_TESTING=ON 
        -DDETRAY_BUILD_TESTING=ON
        -DDETRAY_VC_PLUGIN=OFF
        -DDETRAY_SMATRIX_PLUGIN=OFF
        -DDETRAY_EIGEN_PLUGIN=ON
      - cmake --build build


test_sycl:
  stage: test
  tags: [docker-gpu-nvidia]
  image: "ghcr.io/acts-project/ubuntu2004_oneapi:v30"
  needs:
    - build_sycl
  script:
    - git clone $CLONE_URL src
    - git -C src checkout $HEAD_SHA
    - source src/.github/ci_setup.sh SYCL
    - cd build
    - nvidia-smi
    - ctest --output-on-failure -R ".*sycl.*"
    - find bin -type f -name "*sycl" -not -name "*text*" -exec {} \;
