stages:
  - build
  - test


build_cuda:
  tags: [docker]
  stage: build
  image: ghcr.io/acts-project/ubuntu2004_cuda:v13
  artifacts:
    paths: 
      - build
  script:
      - git clone $CLONE_URL src
      - git -C src checkout $HEAD_SHA
      - >
        cmake -S src -B build 
        -DCMAKE_BUILD_TYPE=Release
        -DBUILD_TESTING=ON 
        -DDETRAY_BUILD_TESTING=ON
        -DDETRAY_BUILD_CUDA=ON
        -DDETRAY_VC_PLUGIN=OFF
        -DDETRAY_SMATRIX_PLUGIN=OFF
        -DDETRAY_EIGEN_PLUGIN=ON
      - cmake --build build


test_cuda:
  stage: test
  tags: [docker-gpu-nvidia]
  image: ghcr.io/acts-project/ubuntu2004_cuda:v13
  needs: 
    - build_cuda
  script:
    - cd build
    - nvidia-smi
    - ctest --output-on-failure -R ".*cuda.*"
    - find bin -type f -name "*cuda" -not -name "*text*" -exec {} \;

