/* Detray library, part of the ACTS project (R&D line)
 *
 * (c) 2025 CERN for the benefit of the ACTS project
 *
 * Mozilla Public License Version 2.0
 *
 * Note: This file is automatically generated.
 *       Do not modify it manually.
 */

#pragma once

#include "detray/definitions/algebra.hpp"
#include "detray/definitions/detail/qualifiers.hpp"

namespace detray::detail {
template <typename jac_matrix_t, typename cov_matrix_t>
DETRAY_HOST_DEVICE void inline transport_covariance_to_bound_impl(
    const cov_matrix_t& C, const jac_matrix_t& J_full, cov_matrix_t& new_C) {
    const auto x4 =
        getter::element(C, 4u, 4u) * getter::element(J_full, 0u, 4u);
    const auto x10 =
        getter::element(C, 4u, 4u) * getter::element(J_full, 1u, 4u);
    const auto x16 =
        getter::element(C, 4u, 4u) * getter::element(J_full, 2u, 4u);
    const auto x22 =
        getter::element(C, 4u, 4u) * getter::element(J_full, 3u, 4u);
    const auto x24 =
        getter::element(C, 4u, 4u) * getter::element(J_full, 5u, 4u);
    const auto x0 =
        getter::element(C, 0u, 0u) * getter::element(J_full, 0u, 0u) +
        getter::element(C, 1u, 0u) * getter::element(J_full, 0u, 1u) +
        getter::element(C, 2u, 0u) * getter::element(J_full, 0u, 2u) +
        getter::element(C, 3u, 0u) * getter::element(J_full, 0u, 3u) +
        getter::element(C, 4u, 0u) * getter::element(J_full, 0u, 4u);
    const auto x1 =
        getter::element(C, 0u, 1u) * getter::element(J_full, 0u, 0u) +
        getter::element(C, 1u, 1u) * getter::element(J_full, 0u, 1u) +
        getter::element(C, 2u, 1u) * getter::element(J_full, 0u, 2u) +
        getter::element(C, 3u, 1u) * getter::element(J_full, 0u, 3u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 0u, 4u);
    const auto x2 =
        getter::element(C, 0u, 2u) * getter::element(J_full, 0u, 0u) +
        getter::element(C, 1u, 2u) * getter::element(J_full, 0u, 1u) +
        getter::element(C, 2u, 2u) * getter::element(J_full, 0u, 2u) +
        getter::element(C, 3u, 2u) * getter::element(J_full, 0u, 3u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 0u, 4u);
    const auto x3 =
        getter::element(C, 0u, 3u) * getter::element(J_full, 0u, 0u) +
        getter::element(C, 1u, 3u) * getter::element(J_full, 0u, 1u) +
        getter::element(C, 2u, 3u) * getter::element(J_full, 0u, 2u) +
        getter::element(C, 3u, 3u) * getter::element(J_full, 0u, 3u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 0u, 4u);
    const auto x6 =
        getter::element(C, 0u, 0u) * getter::element(J_full, 1u, 0u) +
        getter::element(C, 1u, 0u) * getter::element(J_full, 1u, 1u) +
        getter::element(C, 2u, 0u) * getter::element(J_full, 1u, 2u) +
        getter::element(C, 3u, 0u) * getter::element(J_full, 1u, 3u) +
        getter::element(C, 4u, 0u) * getter::element(J_full, 1u, 4u);
    const auto x7 =
        getter::element(C, 0u, 1u) * getter::element(J_full, 1u, 0u) +
        getter::element(C, 1u, 1u) * getter::element(J_full, 1u, 1u) +
        getter::element(C, 2u, 1u) * getter::element(J_full, 1u, 2u) +
        getter::element(C, 3u, 1u) * getter::element(J_full, 1u, 3u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 1u, 4u);
    const auto x8 =
        getter::element(C, 0u, 2u) * getter::element(J_full, 1u, 0u) +
        getter::element(C, 1u, 2u) * getter::element(J_full, 1u, 1u) +
        getter::element(C, 2u, 2u) * getter::element(J_full, 1u, 2u) +
        getter::element(C, 3u, 2u) * getter::element(J_full, 1u, 3u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 1u, 4u);
    const auto x9 =
        getter::element(C, 0u, 3u) * getter::element(J_full, 1u, 0u) +
        getter::element(C, 1u, 3u) * getter::element(J_full, 1u, 1u) +
        getter::element(C, 2u, 3u) * getter::element(J_full, 1u, 2u) +
        getter::element(C, 3u, 3u) * getter::element(J_full, 1u, 3u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 1u, 4u);
    const auto x12 =
        getter::element(C, 0u, 0u) * getter::element(J_full, 2u, 0u) +
        getter::element(C, 1u, 0u) * getter::element(J_full, 2u, 1u) +
        getter::element(C, 2u, 0u) * getter::element(J_full, 2u, 2u) +
        getter::element(C, 3u, 0u) * getter::element(J_full, 2u, 3u) +
        getter::element(C, 4u, 0u) * getter::element(J_full, 2u, 4u);
    const auto x13 =
        getter::element(C, 0u, 1u) * getter::element(J_full, 2u, 0u) +
        getter::element(C, 1u, 1u) * getter::element(J_full, 2u, 1u) +
        getter::element(C, 2u, 1u) * getter::element(J_full, 2u, 2u) +
        getter::element(C, 3u, 1u) * getter::element(J_full, 2u, 3u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 2u, 4u);
    const auto x14 =
        getter::element(C, 0u, 2u) * getter::element(J_full, 2u, 0u) +
        getter::element(C, 1u, 2u) * getter::element(J_full, 2u, 1u) +
        getter::element(C, 2u, 2u) * getter::element(J_full, 2u, 2u) +
        getter::element(C, 3u, 2u) * getter::element(J_full, 2u, 3u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 2u, 4u);
    const auto x15 =
        getter::element(C, 0u, 3u) * getter::element(J_full, 2u, 0u) +
        getter::element(C, 1u, 3u) * getter::element(J_full, 2u, 1u) +
        getter::element(C, 2u, 3u) * getter::element(J_full, 2u, 2u) +
        getter::element(C, 3u, 3u) * getter::element(J_full, 2u, 3u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 2u, 4u);
    const auto x18 =
        getter::element(C, 0u, 0u) * getter::element(J_full, 3u, 0u) +
        getter::element(C, 1u, 0u) * getter::element(J_full, 3u, 1u) +
        getter::element(C, 2u, 0u) * getter::element(J_full, 3u, 2u) +
        getter::element(C, 3u, 0u) * getter::element(J_full, 3u, 3u) +
        getter::element(C, 4u, 0u) * getter::element(J_full, 3u, 4u);
    const auto x19 =
        getter::element(C, 0u, 1u) * getter::element(J_full, 3u, 0u) +
        getter::element(C, 1u, 1u) * getter::element(J_full, 3u, 1u) +
        getter::element(C, 2u, 1u) * getter::element(J_full, 3u, 2u) +
        getter::element(C, 3u, 1u) * getter::element(J_full, 3u, 3u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 3u, 4u);
    const auto x20 =
        getter::element(C, 0u, 2u) * getter::element(J_full, 3u, 0u) +
        getter::element(C, 1u, 2u) * getter::element(J_full, 3u, 1u) +
        getter::element(C, 2u, 2u) * getter::element(J_full, 3u, 2u) +
        getter::element(C, 3u, 2u) * getter::element(J_full, 3u, 3u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 3u, 4u);
    const auto x21 =
        getter::element(C, 0u, 3u) * getter::element(J_full, 3u, 0u) +
        getter::element(C, 1u, 3u) * getter::element(J_full, 3u, 1u) +
        getter::element(C, 2u, 3u) * getter::element(J_full, 3u, 2u) +
        getter::element(C, 3u, 3u) * getter::element(J_full, 3u, 3u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 3u, 4u);
    const auto x25 =
        getter::element(C, 0u, 0u) * getter::element(J_full, 5u, 0u) +
        getter::element(C, 1u, 0u) * getter::element(J_full, 5u, 1u) +
        getter::element(C, 2u, 0u) * getter::element(J_full, 5u, 2u) +
        getter::element(C, 3u, 0u) * getter::element(J_full, 5u, 3u) +
        getter::element(C, 4u, 0u) * getter::element(J_full, 5u, 4u) +
        getter::element(C, 5u, 0u);
    const auto x26 =
        getter::element(C, 0u, 1u) * getter::element(J_full, 5u, 0u) +
        getter::element(C, 1u, 1u) * getter::element(J_full, 5u, 1u) +
        getter::element(C, 2u, 1u) * getter::element(J_full, 5u, 2u) +
        getter::element(C, 3u, 1u) * getter::element(J_full, 5u, 3u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 5u, 4u) +
        getter::element(C, 5u, 1u);
    const auto x27 =
        getter::element(C, 0u, 2u) * getter::element(J_full, 5u, 0u) +
        getter::element(C, 1u, 2u) * getter::element(J_full, 5u, 1u) +
        getter::element(C, 2u, 2u) * getter::element(J_full, 5u, 2u) +
        getter::element(C, 3u, 2u) * getter::element(J_full, 5u, 3u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 5u, 4u) +
        getter::element(C, 5u, 2u);
    const auto x28 =
        getter::element(C, 0u, 3u) * getter::element(J_full, 5u, 0u) +
        getter::element(C, 1u, 3u) * getter::element(J_full, 5u, 1u) +
        getter::element(C, 2u, 3u) * getter::element(J_full, 5u, 2u) +
        getter::element(C, 3u, 3u) * getter::element(J_full, 5u, 3u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 5u, 4u) +
        getter::element(C, 5u, 3u);
    const auto x5 =
        x4 + getter::element(C, 0u, 4u) * getter::element(J_full, 0u, 0u) +
        getter::element(C, 1u, 4u) * getter::element(J_full, 0u, 1u) +
        getter::element(C, 2u, 4u) * getter::element(J_full, 0u, 2u) +
        getter::element(C, 3u, 4u) * getter::element(J_full, 0u, 3u);
    const auto x11 =
        x10 + getter::element(C, 0u, 4u) * getter::element(J_full, 1u, 0u) +
        getter::element(C, 1u, 4u) * getter::element(J_full, 1u, 1u) +
        getter::element(C, 2u, 4u) * getter::element(J_full, 1u, 2u) +
        getter::element(C, 3u, 4u) * getter::element(J_full, 1u, 3u);
    const auto x17 =
        x16 + getter::element(C, 0u, 4u) * getter::element(J_full, 2u, 0u) +
        getter::element(C, 1u, 4u) * getter::element(J_full, 2u, 1u) +
        getter::element(C, 2u, 4u) * getter::element(J_full, 2u, 2u) +
        getter::element(C, 3u, 4u) * getter::element(J_full, 2u, 3u);
    const auto x23 =
        x22 + getter::element(C, 0u, 4u) * getter::element(J_full, 3u, 0u) +
        getter::element(C, 1u, 4u) * getter::element(J_full, 3u, 1u) +
        getter::element(C, 2u, 4u) * getter::element(J_full, 3u, 2u) +
        getter::element(C, 3u, 4u) * getter::element(J_full, 3u, 3u);
    const auto x29 =
        x24 + getter::element(C, 0u, 4u) * getter::element(J_full, 5u, 0u) +
        getter::element(C, 1u, 4u) * getter::element(J_full, 5u, 1u) +
        getter::element(C, 2u, 4u) * getter::element(J_full, 5u, 2u) +
        getter::element(C, 3u, 4u) * getter::element(J_full, 5u, 3u) +
        getter::element(C, 5u, 4u);
    getter::element(new_C, 0u, 0u) = x0 * getter::element(J_full, 0u, 0u) +
                                     x1 * getter::element(J_full, 0u, 1u) +
                                     x2 * getter::element(J_full, 0u, 2u) +
                                     x3 * getter::element(J_full, 0u, 3u) +
                                     x5 * getter::element(J_full, 0u, 4u);
    getter::element(new_C, 1u, 0u) = x11 * getter::element(J_full, 0u, 4u) +
                                     x6 * getter::element(J_full, 0u, 0u) +
                                     x7 * getter::element(J_full, 0u, 1u) +
                                     x8 * getter::element(J_full, 0u, 2u) +
                                     x9 * getter::element(J_full, 0u, 3u);
    getter::element(new_C, 2u, 0u) = x12 * getter::element(J_full, 0u, 0u) +
                                     x13 * getter::element(J_full, 0u, 1u) +
                                     x14 * getter::element(J_full, 0u, 2u) +
                                     x15 * getter::element(J_full, 0u, 3u) +
                                     x17 * getter::element(J_full, 0u, 4u);
    getter::element(new_C, 3u, 0u) = x18 * getter::element(J_full, 0u, 0u) +
                                     x19 * getter::element(J_full, 0u, 1u) +
                                     x20 * getter::element(J_full, 0u, 2u) +
                                     x21 * getter::element(J_full, 0u, 3u) +
                                     x23 * getter::element(J_full, 0u, 4u);
    getter::element(new_C, 4u, 0u) =
        x4 + getter::element(C, 4u, 0u) * getter::element(J_full, 0u, 0u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 0u, 1u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 0u, 2u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 0u, 3u);
    getter::element(new_C, 5u, 0u) = x25 * getter::element(J_full, 0u, 0u) +
                                     x26 * getter::element(J_full, 0u, 1u) +
                                     x27 * getter::element(J_full, 0u, 2u) +
                                     x28 * getter::element(J_full, 0u, 3u) +
                                     x29 * getter::element(J_full, 0u, 4u);
    getter::element(new_C, 0u, 1u) = x0 * getter::element(J_full, 1u, 0u) +
                                     x1 * getter::element(J_full, 1u, 1u) +
                                     x2 * getter::element(J_full, 1u, 2u) +
                                     x3 * getter::element(J_full, 1u, 3u) +
                                     x5 * getter::element(J_full, 1u, 4u);
    getter::element(new_C, 1u, 1u) = x11 * getter::element(J_full, 1u, 4u) +
                                     x6 * getter::element(J_full, 1u, 0u) +
                                     x7 * getter::element(J_full, 1u, 1u) +
                                     x8 * getter::element(J_full, 1u, 2u) +
                                     x9 * getter::element(J_full, 1u, 3u);
    getter::element(new_C, 2u, 1u) = x12 * getter::element(J_full, 1u, 0u) +
                                     x13 * getter::element(J_full, 1u, 1u) +
                                     x14 * getter::element(J_full, 1u, 2u) +
                                     x15 * getter::element(J_full, 1u, 3u) +
                                     x17 * getter::element(J_full, 1u, 4u);
    getter::element(new_C, 3u, 1u) = x18 * getter::element(J_full, 1u, 0u) +
                                     x19 * getter::element(J_full, 1u, 1u) +
                                     x20 * getter::element(J_full, 1u, 2u) +
                                     x21 * getter::element(J_full, 1u, 3u) +
                                     x23 * getter::element(J_full, 1u, 4u);
    getter::element(new_C, 4u, 1u) =
        x10 + getter::element(C, 4u, 0u) * getter::element(J_full, 1u, 0u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 1u, 1u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 1u, 2u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 1u, 3u);
    getter::element(new_C, 5u, 1u) = x25 * getter::element(J_full, 1u, 0u) +
                                     x26 * getter::element(J_full, 1u, 1u) +
                                     x27 * getter::element(J_full, 1u, 2u) +
                                     x28 * getter::element(J_full, 1u, 3u) +
                                     x29 * getter::element(J_full, 1u, 4u);
    getter::element(new_C, 0u, 2u) = x0 * getter::element(J_full, 2u, 0u) +
                                     x1 * getter::element(J_full, 2u, 1u) +
                                     x2 * getter::element(J_full, 2u, 2u) +
                                     x3 * getter::element(J_full, 2u, 3u) +
                                     x5 * getter::element(J_full, 2u, 4u);
    getter::element(new_C, 1u, 2u) = x11 * getter::element(J_full, 2u, 4u) +
                                     x6 * getter::element(J_full, 2u, 0u) +
                                     x7 * getter::element(J_full, 2u, 1u) +
                                     x8 * getter::element(J_full, 2u, 2u) +
                                     x9 * getter::element(J_full, 2u, 3u);
    getter::element(new_C, 2u, 2u) = x12 * getter::element(J_full, 2u, 0u) +
                                     x13 * getter::element(J_full, 2u, 1u) +
                                     x14 * getter::element(J_full, 2u, 2u) +
                                     x15 * getter::element(J_full, 2u, 3u) +
                                     x17 * getter::element(J_full, 2u, 4u);
    getter::element(new_C, 3u, 2u) = x18 * getter::element(J_full, 2u, 0u) +
                                     x19 * getter::element(J_full, 2u, 1u) +
                                     x20 * getter::element(J_full, 2u, 2u) +
                                     x21 * getter::element(J_full, 2u, 3u) +
                                     x23 * getter::element(J_full, 2u, 4u);
    getter::element(new_C, 4u, 2u) =
        x16 + getter::element(C, 4u, 0u) * getter::element(J_full, 2u, 0u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 2u, 1u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 2u, 2u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 2u, 3u);
    getter::element(new_C, 5u, 2u) = x25 * getter::element(J_full, 2u, 0u) +
                                     x26 * getter::element(J_full, 2u, 1u) +
                                     x27 * getter::element(J_full, 2u, 2u) +
                                     x28 * getter::element(J_full, 2u, 3u) +
                                     x29 * getter::element(J_full, 2u, 4u);
    getter::element(new_C, 0u, 3u) = x0 * getter::element(J_full, 3u, 0u) +
                                     x1 * getter::element(J_full, 3u, 1u) +
                                     x2 * getter::element(J_full, 3u, 2u) +
                                     x3 * getter::element(J_full, 3u, 3u) +
                                     x5 * getter::element(J_full, 3u, 4u);
    getter::element(new_C, 1u, 3u) = x11 * getter::element(J_full, 3u, 4u) +
                                     x6 * getter::element(J_full, 3u, 0u) +
                                     x7 * getter::element(J_full, 3u, 1u) +
                                     x8 * getter::element(J_full, 3u, 2u) +
                                     x9 * getter::element(J_full, 3u, 3u);
    getter::element(new_C, 2u, 3u) = x12 * getter::element(J_full, 3u, 0u) +
                                     x13 * getter::element(J_full, 3u, 1u) +
                                     x14 * getter::element(J_full, 3u, 2u) +
                                     x15 * getter::element(J_full, 3u, 3u) +
                                     x17 * getter::element(J_full, 3u, 4u);
    getter::element(new_C, 3u, 3u) = x18 * getter::element(J_full, 3u, 0u) +
                                     x19 * getter::element(J_full, 3u, 1u) +
                                     x20 * getter::element(J_full, 3u, 2u) +
                                     x21 * getter::element(J_full, 3u, 3u) +
                                     x23 * getter::element(J_full, 3u, 4u);
    getter::element(new_C, 4u, 3u) =
        x22 + getter::element(C, 4u, 0u) * getter::element(J_full, 3u, 0u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 3u, 1u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 3u, 2u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 3u, 3u);
    getter::element(new_C, 5u, 3u) = x25 * getter::element(J_full, 3u, 0u) +
                                     x26 * getter::element(J_full, 3u, 1u) +
                                     x27 * getter::element(J_full, 3u, 2u) +
                                     x28 * getter::element(J_full, 3u, 3u) +
                                     x29 * getter::element(J_full, 3u, 4u);
    getter::element(new_C, 0u, 4u) = x5;
    getter::element(new_C, 1u, 4u) = x11;
    getter::element(new_C, 2u, 4u) = x17;
    getter::element(new_C, 3u, 4u) = x23;
    getter::element(new_C, 4u, 4u) = getter::element(C, 4u, 4u);
    getter::element(new_C, 5u, 4u) = x29;
    getter::element(new_C, 0u, 5u) =
        x0 * getter::element(J_full, 5u, 0u) +
        x1 * getter::element(J_full, 5u, 1u) +
        x2 * getter::element(J_full, 5u, 2u) +
        x3 * getter::element(J_full, 5u, 3u) +
        x5 * getter::element(J_full, 5u, 4u) +
        getter::element(C, 0u, 5u) * getter::element(J_full, 0u, 0u) +
        getter::element(C, 1u, 5u) * getter::element(J_full, 0u, 1u) +
        getter::element(C, 2u, 5u) * getter::element(J_full, 0u, 2u) +
        getter::element(C, 3u, 5u) * getter::element(J_full, 0u, 3u) +
        getter::element(C, 4u, 5u) * getter::element(J_full, 0u, 4u);
    getter::element(new_C, 1u, 5u) =
        x11 * getter::element(J_full, 5u, 4u) +
        x6 * getter::element(J_full, 5u, 0u) +
        x7 * getter::element(J_full, 5u, 1u) +
        x8 * getter::element(J_full, 5u, 2u) +
        x9 * getter::element(J_full, 5u, 3u) +
        getter::element(C, 0u, 5u) * getter::element(J_full, 1u, 0u) +
        getter::element(C, 1u, 5u) * getter::element(J_full, 1u, 1u) +
        getter::element(C, 2u, 5u) * getter::element(J_full, 1u, 2u) +
        getter::element(C, 3u, 5u) * getter::element(J_full, 1u, 3u) +
        getter::element(C, 4u, 5u) * getter::element(J_full, 1u, 4u);
    getter::element(new_C, 2u, 5u) =
        x12 * getter::element(J_full, 5u, 0u) +
        x13 * getter::element(J_full, 5u, 1u) +
        x14 * getter::element(J_full, 5u, 2u) +
        x15 * getter::element(J_full, 5u, 3u) +
        x17 * getter::element(J_full, 5u, 4u) +
        getter::element(C, 0u, 5u) * getter::element(J_full, 2u, 0u) +
        getter::element(C, 1u, 5u) * getter::element(J_full, 2u, 1u) +
        getter::element(C, 2u, 5u) * getter::element(J_full, 2u, 2u) +
        getter::element(C, 3u, 5u) * getter::element(J_full, 2u, 3u) +
        getter::element(C, 4u, 5u) * getter::element(J_full, 2u, 4u);
    getter::element(new_C, 3u, 5u) =
        x18 * getter::element(J_full, 5u, 0u) +
        x19 * getter::element(J_full, 5u, 1u) +
        x20 * getter::element(J_full, 5u, 2u) +
        x21 * getter::element(J_full, 5u, 3u) +
        x23 * getter::element(J_full, 5u, 4u) +
        getter::element(C, 0u, 5u) * getter::element(J_full, 3u, 0u) +
        getter::element(C, 1u, 5u) * getter::element(J_full, 3u, 1u) +
        getter::element(C, 2u, 5u) * getter::element(J_full, 3u, 2u) +
        getter::element(C, 3u, 5u) * getter::element(J_full, 3u, 3u) +
        getter::element(C, 4u, 5u) * getter::element(J_full, 3u, 4u);
    getter::element(new_C, 4u, 5u) =
        x24 + getter::element(C, 4u, 0u) * getter::element(J_full, 5u, 0u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 5u, 1u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 5u, 2u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 5u, 3u) +
        getter::element(C, 4u, 5u);
    getter::element(new_C, 5u, 5u) =
        x25 * getter::element(J_full, 5u, 0u) +
        x26 * getter::element(J_full, 5u, 1u) +
        x27 * getter::element(J_full, 5u, 2u) +
        x28 * getter::element(J_full, 5u, 3u) +
        x29 * getter::element(J_full, 5u, 4u) +
        getter::element(C, 0u, 5u) * getter::element(J_full, 5u, 0u) +
        getter::element(C, 1u, 5u) * getter::element(J_full, 5u, 1u) +
        getter::element(C, 2u, 5u) * getter::element(J_full, 5u, 2u) +
        getter::element(C, 3u, 5u) * getter::element(J_full, 5u, 3u) +
        getter::element(C, 4u, 5u) * getter::element(J_full, 5u, 4u) +
        getter::element(C, 5u, 5u);
}
}  // namespace detray::detail
