/* Detray library, part of the ACTS project (R&D line)
 *
 * (c) 2025 CERN for the benefit of the ACTS project
 *
 * Mozilla Public License Version 2.0
 *
 * Note: This file is automatically generated.
 *       Do not modify it manually.
 */

#pragma once

#include "detray/algebra/type_traits.hpp"
#include "detray/definitions/algebra.hpp"
#include "detray/definitions/detail/qualifiers.hpp"

namespace detray::detail {
template <typename J_transport_t, typename dFdt_t, typename dGdt_t,
          typename dFdqop_t, typename dGdqop_t, typename dqopqop_t,
          typename new_J_t>
DETRAY_HOST_DEVICE void inline update_transport_jacobian_without_gradient_impl(
    const J_transport_t& J_transport, const dFdt_t& dFdt, const dGdt_t& dGdt,
    const dFdqop_t& dFdqop, const dGdqop_t& dGdqop, const dqopqop_t& dqopqop,
    new_J_t& new_J)
    requires((algebra::concepts::square_matrix<J_transport_t> &&
              algebra::traits::rank<J_transport_t> == 8) &&
             (algebra::concepts::square_matrix<dFdt_t> &&
              algebra::traits::rank<dFdt_t> == 3) &&
             (algebra::concepts::square_matrix<dGdt_t> &&
              algebra::traits::rank<dGdt_t> == 3) &&
             (algebra::concepts::vector3D<dFdqop_t>) &&
             (algebra::concepts::vector3D<dGdqop_t>) &&
             (algebra::concepts::scalar<dqopqop_t>) &&
             (algebra::concepts::square_matrix<new_J_t> &&
              algebra::traits::rank<new_J_t> == 8))
{
    assert(getter::element(J_transport, 0u, 0u) == 1.f);
    assert(getter::element(J_transport, 0u, 1u) == 0.f);
    assert(getter::element(J_transport, 0u, 2u) == 0.f);
    assert(getter::element(J_transport, 0u, 3u) == 0.f);
    assert(getter::element(J_transport, 1u, 0u) == 0.f);
    assert(getter::element(J_transport, 1u, 1u) == 1.f);
    assert(getter::element(J_transport, 1u, 2u) == 0.f);
    assert(getter::element(J_transport, 1u, 3u) == 0.f);
    assert(getter::element(J_transport, 2u, 0u) == 0.f);
    assert(getter::element(J_transport, 2u, 1u) == 0.f);
    assert(getter::element(J_transport, 2u, 2u) == 1.f);
    assert(getter::element(J_transport, 2u, 3u) == 0.f);
    assert(getter::element(J_transport, 3u, 0u) == 0.f);
    assert(getter::element(J_transport, 3u, 1u) == 0.f);
    assert(getter::element(J_transport, 3u, 2u) == 0.f);
    assert(getter::element(J_transport, 3u, 3u) == 1.f);
    assert(getter::element(J_transport, 3u, 4u) == 0.f);
    assert(getter::element(J_transport, 3u, 5u) == 0.f);
    assert(getter::element(J_transport, 3u, 6u) == 0.f);
    assert(getter::element(J_transport, 3u, 7u) == 0.f);
    assert(getter::element(J_transport, 4u, 0u) == 0.f);
    assert(getter::element(J_transport, 4u, 1u) == 0.f);
    assert(getter::element(J_transport, 4u, 2u) == 0.f);
    assert(getter::element(J_transport, 4u, 3u) == 0.f);
    assert(getter::element(J_transport, 5u, 0u) == 0.f);
    assert(getter::element(J_transport, 5u, 1u) == 0.f);
    assert(getter::element(J_transport, 5u, 2u) == 0.f);
    assert(getter::element(J_transport, 5u, 3u) == 0.f);
    assert(getter::element(J_transport, 6u, 0u) == 0.f);
    assert(getter::element(J_transport, 6u, 1u) == 0.f);
    assert(getter::element(J_transport, 6u, 2u) == 0.f);
    assert(getter::element(J_transport, 6u, 3u) == 0.f);
    assert(getter::element(J_transport, 7u, 0u) == 0.f);
    assert(getter::element(J_transport, 7u, 1u) == 0.f);
    assert(getter::element(J_transport, 7u, 2u) == 0.f);
    assert(getter::element(J_transport, 7u, 3u) == 0.f);
    assert(getter::element(J_transport, 7u, 4u) == 0.f);
    assert(getter::element(J_transport, 7u, 5u) == 0.f);
    assert(getter::element(J_transport, 7u, 6u) == 0.f);
    getter::element(new_J, 0u, 0u) = 1;
    getter::element(new_J, 1u, 0u) = 0;
    getter::element(new_J, 2u, 0u) = 0;
    getter::element(new_J, 3u, 0u) = 0;
    getter::element(new_J, 4u, 0u) = 0;
    getter::element(new_J, 5u, 0u) = 0;
    getter::element(new_J, 6u, 0u) = 0;
    getter::element(new_J, 7u, 0u) = 0;
    getter::element(new_J, 0u, 1u) = 0;
    getter::element(new_J, 1u, 1u) = 1;
    getter::element(new_J, 2u, 1u) = 0;
    getter::element(new_J, 3u, 1u) = 0;
    getter::element(new_J, 4u, 1u) = 0;
    getter::element(new_J, 5u, 1u) = 0;
    getter::element(new_J, 6u, 1u) = 0;
    getter::element(new_J, 7u, 1u) = 0;
    getter::element(new_J, 0u, 2u) = 0;
    getter::element(new_J, 1u, 2u) = 0;
    getter::element(new_J, 2u, 2u) = 1;
    getter::element(new_J, 3u, 2u) = 0;
    getter::element(new_J, 4u, 2u) = 0;
    getter::element(new_J, 5u, 2u) = 0;
    getter::element(new_J, 6u, 2u) = 0;
    getter::element(new_J, 7u, 2u) = 0;
    getter::element(new_J, 0u, 3u) = 0;
    getter::element(new_J, 1u, 3u) = 0;
    getter::element(new_J, 2u, 3u) = 0;
    getter::element(new_J, 3u, 3u) = 1;
    getter::element(new_J, 4u, 3u) = 0;
    getter::element(new_J, 5u, 3u) = 0;
    getter::element(new_J, 6u, 3u) = 0;
    getter::element(new_J, 7u, 3u) = 0;
    getter::element(new_J, 0u, 4u) =
        getter::element(J_transport, 0u, 4u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dFdt, 0u, 2u);
    getter::element(new_J, 1u, 4u) =
        getter::element(J_transport, 1u, 4u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dFdt, 1u, 2u);
    getter::element(new_J, 2u, 4u) =
        getter::element(J_transport, 2u, 4u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dFdt, 2u, 2u);
    getter::element(new_J, 3u, 4u) = 0;
    getter::element(new_J, 4u, 4u) =
        getter::element(J_transport, 4u, 4u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dGdt, 0u, 2u);
    getter::element(new_J, 5u, 4u) =
        getter::element(J_transport, 4u, 4u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dGdt, 1u, 2u);
    getter::element(new_J, 6u, 4u) =
        getter::element(J_transport, 4u, 4u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dGdt, 2u, 2u);
    getter::element(new_J, 7u, 4u) = 0;
    getter::element(new_J, 0u, 5u) =
        getter::element(J_transport, 0u, 5u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dFdt, 0u, 2u);
    getter::element(new_J, 1u, 5u) =
        getter::element(J_transport, 1u, 5u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dFdt, 1u, 2u);
    getter::element(new_J, 2u, 5u) =
        getter::element(J_transport, 2u, 5u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dFdt, 2u, 2u);
    getter::element(new_J, 3u, 5u) = 0;
    getter::element(new_J, 4u, 5u) =
        getter::element(J_transport, 4u, 5u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dGdt, 0u, 2u);
    getter::element(new_J, 5u, 5u) =
        getter::element(J_transport, 4u, 5u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dGdt, 1u, 2u);
    getter::element(new_J, 6u, 5u) =
        getter::element(J_transport, 4u, 5u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dGdt, 2u, 2u);
    getter::element(new_J, 7u, 5u) = 0;
    getter::element(new_J, 0u, 6u) =
        getter::element(J_transport, 0u, 6u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dFdt, 0u, 2u);
    getter::element(new_J, 1u, 6u) =
        getter::element(J_transport, 1u, 6u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dFdt, 1u, 2u);
    getter::element(new_J, 2u, 6u) =
        getter::element(J_transport, 2u, 6u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dFdt, 2u, 2u);
    getter::element(new_J, 3u, 6u) = 0;
    getter::element(new_J, 4u, 6u) =
        getter::element(J_transport, 4u, 6u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dGdt, 0u, 2u);
    getter::element(new_J, 5u, 6u) =
        getter::element(J_transport, 4u, 6u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dGdt, 1u, 2u);
    getter::element(new_J, 6u, 6u) =
        getter::element(J_transport, 4u, 6u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dGdt, 2u, 2u);
    getter::element(new_J, 7u, 6u) = 0;
    getter::element(new_J, 0u, 7u) =
        getter::element(J_transport, 0u, 7u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 7u) =
        getter::element(J_transport, 1u, 7u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 7u) =
        getter::element(J_transport, 2u, 7u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 7u) = 0;
    getter::element(new_J, 4u, 7u) =
        getter::element(J_transport, 4u, 7u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 7u) =
        getter::element(J_transport, 4u, 7u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 7u) =
        getter::element(J_transport, 4u, 7u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 7u) =
        dqopqop * getter::element(J_transport, 7u, 7u);
}
template <typename J_transport_t, typename dFdt_t, typename dGdt_t,
          typename dFdr_t, typename dGdr_t, typename dFdqop_t,
          typename dGdqop_t, typename dqopqop_t, typename new_J_t>
DETRAY_HOST_DEVICE void inline update_transport_jacobian_with_gradient_impl(
    const J_transport_t& J_transport, const dFdt_t& dFdt, const dGdt_t& dGdt,
    const dFdr_t& dFdr, const dGdr_t& dGdr, const dFdqop_t& dFdqop,
    const dGdqop_t& dGdqop, const dqopqop_t& dqopqop, new_J_t& new_J)
    requires((algebra::concepts::square_matrix<J_transport_t> &&
              algebra::traits::rank<J_transport_t> == 8) &&
             (algebra::concepts::square_matrix<dFdt_t> &&
              algebra::traits::rank<dFdt_t> == 3) &&
             (algebra::concepts::square_matrix<dGdt_t> &&
              algebra::traits::rank<dGdt_t> == 3) &&
             (algebra::concepts::square_matrix<dFdr_t> &&
              algebra::traits::rank<dFdr_t> == 3) &&
             (algebra::concepts::square_matrix<dGdr_t> &&
              algebra::traits::rank<dGdr_t> == 3) &&
             (algebra::concepts::vector3D<dFdqop_t>) &&
             (algebra::concepts::vector3D<dGdqop_t>) &&
             (algebra::concepts::scalar<dqopqop_t>) &&
             (algebra::concepts::square_matrix<new_J_t> &&
              algebra::traits::rank<new_J_t> == 8))
{
    assert(getter::element(J_transport, 0u, 3u) == 0.f);
    assert(getter::element(J_transport, 1u, 3u) == 0.f);
    assert(getter::element(J_transport, 2u, 3u) == 0.f);
    assert(getter::element(J_transport, 3u, 0u) == 0.f);
    assert(getter::element(J_transport, 3u, 1u) == 0.f);
    assert(getter::element(J_transport, 3u, 2u) == 0.f);
    assert(getter::element(J_transport, 3u, 3u) == 1.f);
    assert(getter::element(J_transport, 3u, 4u) == 0.f);
    assert(getter::element(J_transport, 3u, 5u) == 0.f);
    assert(getter::element(J_transport, 3u, 6u) == 0.f);
    assert(getter::element(J_transport, 3u, 7u) == 0.f);
    assert(getter::element(J_transport, 4u, 3u) == 0.f);
    assert(getter::element(J_transport, 5u, 3u) == 0.f);
    assert(getter::element(J_transport, 6u, 3u) == 0.f);
    assert(getter::element(J_transport, 7u, 0u) == 0.f);
    assert(getter::element(J_transport, 7u, 1u) == 0.f);
    assert(getter::element(J_transport, 7u, 2u) == 0.f);
    assert(getter::element(J_transport, 7u, 3u) == 0.f);
    assert(getter::element(J_transport, 7u, 4u) == 0.f);
    assert(getter::element(J_transport, 7u, 5u) == 0.f);
    assert(getter::element(J_transport, 7u, 6u) == 0.f);
    getter::element(new_J, 0u, 0u) =
        getter::element(J_transport, 0u, 0u) * getter::element(dFdr, 0u, 0u) +
        getter::element(J_transport, 1u, 0u) * getter::element(dFdr, 0u, 1u) +
        getter::element(J_transport, 2u, 0u) * getter::element(dFdr, 0u, 2u) +
        getter::element(J_transport, 4u, 0u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dFdt, 0u, 2u);
    getter::element(new_J, 1u, 0u) =
        getter::element(J_transport, 0u, 0u) * getter::element(dFdr, 1u, 0u) +
        getter::element(J_transport, 1u, 0u) * getter::element(dFdr, 1u, 1u) +
        getter::element(J_transport, 2u, 0u) * getter::element(dFdr, 1u, 2u) +
        getter::element(J_transport, 4u, 0u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dFdt, 1u, 2u);
    getter::element(new_J, 2u, 0u) =
        getter::element(J_transport, 0u, 0u) * getter::element(dFdr, 2u, 0u) +
        getter::element(J_transport, 1u, 0u) * getter::element(dFdr, 2u, 1u) +
        getter::element(J_transport, 2u, 0u) * getter::element(dFdr, 2u, 2u) +
        getter::element(J_transport, 4u, 0u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dFdt, 2u, 2u);
    getter::element(new_J, 3u, 0u) = 0;
    getter::element(new_J, 4u, 0u) =
        getter::element(J_transport, 0u, 0u) * getter::element(dGdr, 0u, 0u) +
        getter::element(J_transport, 1u, 0u) * getter::element(dGdr, 0u, 1u) +
        getter::element(J_transport, 2u, 0u) * getter::element(dGdr, 0u, 2u) +
        getter::element(J_transport, 4u, 0u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dGdt, 0u, 2u);
    getter::element(new_J, 5u, 0u) =
        getter::element(J_transport, 0u, 0u) * getter::element(dGdr, 1u, 0u) +
        getter::element(J_transport, 1u, 0u) * getter::element(dGdr, 1u, 1u) +
        getter::element(J_transport, 2u, 0u) * getter::element(dGdr, 1u, 2u) +
        getter::element(J_transport, 4u, 0u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dGdt, 1u, 2u);
    getter::element(new_J, 6u, 0u) =
        getter::element(J_transport, 0u, 0u) * getter::element(dGdr, 2u, 0u) +
        getter::element(J_transport, 1u, 0u) * getter::element(dGdr, 2u, 1u) +
        getter::element(J_transport, 2u, 0u) * getter::element(dGdr, 2u, 2u) +
        getter::element(J_transport, 4u, 0u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dGdt, 2u, 2u);
    getter::element(new_J, 7u, 0u) = 0;
    getter::element(new_J, 0u, 1u) =
        getter::element(J_transport, 0u, 1u) * getter::element(dFdr, 0u, 0u) +
        getter::element(J_transport, 1u, 1u) * getter::element(dFdr, 0u, 1u) +
        getter::element(J_transport, 2u, 1u) * getter::element(dFdr, 0u, 2u) +
        getter::element(J_transport, 4u, 1u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dFdt, 0u, 2u);
    getter::element(new_J, 1u, 1u) =
        getter::element(J_transport, 0u, 1u) * getter::element(dFdr, 1u, 0u) +
        getter::element(J_transport, 1u, 1u) * getter::element(dFdr, 1u, 1u) +
        getter::element(J_transport, 2u, 1u) * getter::element(dFdr, 1u, 2u) +
        getter::element(J_transport, 4u, 1u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dFdt, 1u, 2u);
    getter::element(new_J, 2u, 1u) =
        getter::element(J_transport, 0u, 1u) * getter::element(dFdr, 2u, 0u) +
        getter::element(J_transport, 1u, 1u) * getter::element(dFdr, 2u, 1u) +
        getter::element(J_transport, 2u, 1u) * getter::element(dFdr, 2u, 2u) +
        getter::element(J_transport, 4u, 1u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dFdt, 2u, 2u);
    getter::element(new_J, 3u, 1u) = 0;
    getter::element(new_J, 4u, 1u) =
        getter::element(J_transport, 0u, 1u) * getter::element(dGdr, 0u, 0u) +
        getter::element(J_transport, 1u, 1u) * getter::element(dGdr, 0u, 1u) +
        getter::element(J_transport, 2u, 1u) * getter::element(dGdr, 0u, 2u) +
        getter::element(J_transport, 4u, 1u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dGdt, 0u, 2u);
    getter::element(new_J, 5u, 1u) =
        getter::element(J_transport, 0u, 1u) * getter::element(dGdr, 1u, 0u) +
        getter::element(J_transport, 1u, 1u) * getter::element(dGdr, 1u, 1u) +
        getter::element(J_transport, 2u, 1u) * getter::element(dGdr, 1u, 2u) +
        getter::element(J_transport, 4u, 1u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dGdt, 1u, 2u);
    getter::element(new_J, 6u, 1u) =
        getter::element(J_transport, 0u, 1u) * getter::element(dGdr, 2u, 0u) +
        getter::element(J_transport, 1u, 1u) * getter::element(dGdr, 2u, 1u) +
        getter::element(J_transport, 2u, 1u) * getter::element(dGdr, 2u, 2u) +
        getter::element(J_transport, 4u, 1u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dGdt, 2u, 2u);
    getter::element(new_J, 7u, 1u) = 0;
    getter::element(new_J, 0u, 2u) =
        getter::element(J_transport, 0u, 2u) * getter::element(dFdr, 0u, 0u) +
        getter::element(J_transport, 1u, 2u) * getter::element(dFdr, 0u, 1u) +
        getter::element(J_transport, 2u, 2u) * getter::element(dFdr, 0u, 2u) +
        getter::element(J_transport, 4u, 2u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dFdt, 0u, 2u);
    getter::element(new_J, 1u, 2u) =
        getter::element(J_transport, 0u, 2u) * getter::element(dFdr, 1u, 0u) +
        getter::element(J_transport, 1u, 2u) * getter::element(dFdr, 1u, 1u) +
        getter::element(J_transport, 2u, 2u) * getter::element(dFdr, 1u, 2u) +
        getter::element(J_transport, 4u, 2u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dFdt, 1u, 2u);
    getter::element(new_J, 2u, 2u) =
        getter::element(J_transport, 0u, 2u) * getter::element(dFdr, 2u, 0u) +
        getter::element(J_transport, 1u, 2u) * getter::element(dFdr, 2u, 1u) +
        getter::element(J_transport, 2u, 2u) * getter::element(dFdr, 2u, 2u) +
        getter::element(J_transport, 4u, 2u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dFdt, 2u, 2u);
    getter::element(new_J, 3u, 2u) = 0;
    getter::element(new_J, 4u, 2u) =
        getter::element(J_transport, 0u, 2u) * getter::element(dGdr, 0u, 0u) +
        getter::element(J_transport, 1u, 2u) * getter::element(dGdr, 0u, 1u) +
        getter::element(J_transport, 2u, 2u) * getter::element(dGdr, 0u, 2u) +
        getter::element(J_transport, 4u, 2u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dGdt, 0u, 2u);
    getter::element(new_J, 5u, 2u) =
        getter::element(J_transport, 0u, 2u) * getter::element(dGdr, 1u, 0u) +
        getter::element(J_transport, 1u, 2u) * getter::element(dGdr, 1u, 1u) +
        getter::element(J_transport, 2u, 2u) * getter::element(dGdr, 1u, 2u) +
        getter::element(J_transport, 4u, 2u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dGdt, 1u, 2u);
    getter::element(new_J, 6u, 2u) =
        getter::element(J_transport, 0u, 2u) * getter::element(dGdr, 2u, 0u) +
        getter::element(J_transport, 1u, 2u) * getter::element(dGdr, 2u, 1u) +
        getter::element(J_transport, 2u, 2u) * getter::element(dGdr, 2u, 2u) +
        getter::element(J_transport, 4u, 2u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dGdt, 2u, 2u);
    getter::element(new_J, 7u, 2u) = 0;
    getter::element(new_J, 0u, 3u) = 0;
    getter::element(new_J, 1u, 3u) = 0;
    getter::element(new_J, 2u, 3u) = 0;
    getter::element(new_J, 3u, 3u) = 1;
    getter::element(new_J, 4u, 3u) = 0;
    getter::element(new_J, 5u, 3u) = 0;
    getter::element(new_J, 6u, 3u) = 0;
    getter::element(new_J, 7u, 3u) = 0;
    getter::element(new_J, 0u, 4u) =
        getter::element(J_transport, 0u, 4u) * getter::element(dFdr, 0u, 0u) +
        getter::element(J_transport, 1u, 4u) * getter::element(dFdr, 0u, 1u) +
        getter::element(J_transport, 2u, 4u) * getter::element(dFdr, 0u, 2u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dFdt, 0u, 2u);
    getter::element(new_J, 1u, 4u) =
        getter::element(J_transport, 0u, 4u) * getter::element(dFdr, 1u, 0u) +
        getter::element(J_transport, 1u, 4u) * getter::element(dFdr, 1u, 1u) +
        getter::element(J_transport, 2u, 4u) * getter::element(dFdr, 1u, 2u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dFdt, 1u, 2u);
    getter::element(new_J, 2u, 4u) =
        getter::element(J_transport, 0u, 4u) * getter::element(dFdr, 2u, 0u) +
        getter::element(J_transport, 1u, 4u) * getter::element(dFdr, 2u, 1u) +
        getter::element(J_transport, 2u, 4u) * getter::element(dFdr, 2u, 2u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dFdt, 2u, 2u);
    getter::element(new_J, 3u, 4u) = 0;
    getter::element(new_J, 4u, 4u) =
        getter::element(J_transport, 0u, 4u) * getter::element(dGdr, 0u, 0u) +
        getter::element(J_transport, 1u, 4u) * getter::element(dGdr, 0u, 1u) +
        getter::element(J_transport, 2u, 4u) * getter::element(dGdr, 0u, 2u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dGdt, 0u, 2u);
    getter::element(new_J, 5u, 4u) =
        getter::element(J_transport, 0u, 4u) * getter::element(dGdr, 1u, 0u) +
        getter::element(J_transport, 1u, 4u) * getter::element(dGdr, 1u, 1u) +
        getter::element(J_transport, 2u, 4u) * getter::element(dGdr, 1u, 2u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dGdt, 1u, 2u);
    getter::element(new_J, 6u, 4u) =
        getter::element(J_transport, 0u, 4u) * getter::element(dGdr, 2u, 0u) +
        getter::element(J_transport, 1u, 4u) * getter::element(dGdr, 2u, 1u) +
        getter::element(J_transport, 2u, 4u) * getter::element(dGdr, 2u, 2u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dGdt, 2u, 2u);
    getter::element(new_J, 7u, 4u) = 0;
    getter::element(new_J, 0u, 5u) =
        getter::element(J_transport, 0u, 5u) * getter::element(dFdr, 0u, 0u) +
        getter::element(J_transport, 1u, 5u) * getter::element(dFdr, 0u, 1u) +
        getter::element(J_transport, 2u, 5u) * getter::element(dFdr, 0u, 2u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dFdt, 0u, 2u);
    getter::element(new_J, 1u, 5u) =
        getter::element(J_transport, 0u, 5u) * getter::element(dFdr, 1u, 0u) +
        getter::element(J_transport, 1u, 5u) * getter::element(dFdr, 1u, 1u) +
        getter::element(J_transport, 2u, 5u) * getter::element(dFdr, 1u, 2u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dFdt, 1u, 2u);
    getter::element(new_J, 2u, 5u) =
        getter::element(J_transport, 0u, 5u) * getter::element(dFdr, 2u, 0u) +
        getter::element(J_transport, 1u, 5u) * getter::element(dFdr, 2u, 1u) +
        getter::element(J_transport, 2u, 5u) * getter::element(dFdr, 2u, 2u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dFdt, 2u, 2u);
    getter::element(new_J, 3u, 5u) = 0;
    getter::element(new_J, 4u, 5u) =
        getter::element(J_transport, 0u, 5u) * getter::element(dGdr, 0u, 0u) +
        getter::element(J_transport, 1u, 5u) * getter::element(dGdr, 0u, 1u) +
        getter::element(J_transport, 2u, 5u) * getter::element(dGdr, 0u, 2u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dGdt, 0u, 2u);
    getter::element(new_J, 5u, 5u) =
        getter::element(J_transport, 0u, 5u) * getter::element(dGdr, 1u, 0u) +
        getter::element(J_transport, 1u, 5u) * getter::element(dGdr, 1u, 1u) +
        getter::element(J_transport, 2u, 5u) * getter::element(dGdr, 1u, 2u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dGdt, 1u, 2u);
    getter::element(new_J, 6u, 5u) =
        getter::element(J_transport, 0u, 5u) * getter::element(dGdr, 2u, 0u) +
        getter::element(J_transport, 1u, 5u) * getter::element(dGdr, 2u, 1u) +
        getter::element(J_transport, 2u, 5u) * getter::element(dGdr, 2u, 2u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dGdt, 2u, 2u);
    getter::element(new_J, 7u, 5u) = 0;
    getter::element(new_J, 0u, 6u) =
        getter::element(J_transport, 0u, 6u) * getter::element(dFdr, 0u, 0u) +
        getter::element(J_transport, 1u, 6u) * getter::element(dFdr, 0u, 1u) +
        getter::element(J_transport, 2u, 6u) * getter::element(dFdr, 0u, 2u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dFdt, 0u, 2u);
    getter::element(new_J, 1u, 6u) =
        getter::element(J_transport, 0u, 6u) * getter::element(dFdr, 1u, 0u) +
        getter::element(J_transport, 1u, 6u) * getter::element(dFdr, 1u, 1u) +
        getter::element(J_transport, 2u, 6u) * getter::element(dFdr, 1u, 2u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dFdt, 1u, 2u);
    getter::element(new_J, 2u, 6u) =
        getter::element(J_transport, 0u, 6u) * getter::element(dFdr, 2u, 0u) +
        getter::element(J_transport, 1u, 6u) * getter::element(dFdr, 2u, 1u) +
        getter::element(J_transport, 2u, 6u) * getter::element(dFdr, 2u, 2u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dFdt, 2u, 2u);
    getter::element(new_J, 3u, 6u) = 0;
    getter::element(new_J, 4u, 6u) =
        getter::element(J_transport, 0u, 6u) * getter::element(dGdr, 0u, 0u) +
        getter::element(J_transport, 1u, 6u) * getter::element(dGdr, 0u, 1u) +
        getter::element(J_transport, 2u, 6u) * getter::element(dGdr, 0u, 2u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dGdt, 0u, 2u);
    getter::element(new_J, 5u, 6u) =
        getter::element(J_transport, 0u, 6u) * getter::element(dGdr, 1u, 0u) +
        getter::element(J_transport, 1u, 6u) * getter::element(dGdr, 1u, 1u) +
        getter::element(J_transport, 2u, 6u) * getter::element(dGdr, 1u, 2u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dGdt, 1u, 2u);
    getter::element(new_J, 6u, 6u) =
        getter::element(J_transport, 0u, 6u) * getter::element(dGdr, 2u, 0u) +
        getter::element(J_transport, 1u, 6u) * getter::element(dGdr, 2u, 1u) +
        getter::element(J_transport, 2u, 6u) * getter::element(dGdr, 2u, 2u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dGdt, 2u, 2u);
    getter::element(new_J, 7u, 6u) = 0;
    getter::element(new_J, 0u, 7u) =
        getter::element(J_transport, 0u, 7u) * getter::element(dFdr, 0u, 0u) +
        getter::element(J_transport, 1u, 7u) * getter::element(dFdr, 0u, 1u) +
        getter::element(J_transport, 2u, 7u) * getter::element(dFdr, 0u, 2u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 7u) =
        getter::element(J_transport, 0u, 7u) * getter::element(dFdr, 1u, 0u) +
        getter::element(J_transport, 1u, 7u) * getter::element(dFdr, 1u, 1u) +
        getter::element(J_transport, 2u, 7u) * getter::element(dFdr, 1u, 2u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 7u) =
        getter::element(J_transport, 0u, 7u) * getter::element(dFdr, 2u, 0u) +
        getter::element(J_transport, 1u, 7u) * getter::element(dFdr, 2u, 1u) +
        getter::element(J_transport, 2u, 7u) * getter::element(dFdr, 2u, 2u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 7u) = 0;
    getter::element(new_J, 4u, 7u) =
        getter::element(J_transport, 0u, 7u) * getter::element(dGdr, 0u, 0u) +
        getter::element(J_transport, 1u, 7u) * getter::element(dGdr, 0u, 1u) +
        getter::element(J_transport, 2u, 7u) * getter::element(dGdr, 0u, 2u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 7u) =
        getter::element(J_transport, 0u, 7u) * getter::element(dGdr, 1u, 0u) +
        getter::element(J_transport, 1u, 7u) * getter::element(dGdr, 1u, 1u) +
        getter::element(J_transport, 2u, 7u) * getter::element(dGdr, 1u, 2u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 7u) =
        getter::element(J_transport, 0u, 7u) * getter::element(dGdr, 2u, 0u) +
        getter::element(J_transport, 1u, 7u) * getter::element(dGdr, 2u, 1u) +
        getter::element(J_transport, 2u, 7u) * getter::element(dGdr, 2u, 2u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 7u) =
        dqopqop * getter::element(J_transport, 7u, 7u);
}
}  // namespace detray::detail
