/* Detray library, part of the ACTS project (R&D line)
 *
 * (c) 2025 CERN for the benefit of the ACTS project
 *
 * Mozilla Public License Version 2.0
 *
 * Note: This file is automatically generated.
 *       Do not modify it manually.
 */

#pragma once

#include "detray/definitions/algebra.hpp"
#include "detray/definitions/detail/qualifiers.hpp"

namespace detray::detail {
template <typename jac_matrix_t, typename matrix33_t, typename matrix31_t,
          typename scalar_t>
DETRAY_HOST_DEVICE void inline update_transport_jacobian_without_gradient_impl(
    const jac_matrix_t& J_transport, const matrix33_t& dFdt,
    const matrix33_t& dGdt, const matrix31_t& dFdqop, const matrix31_t& dGdqop,
    const scalar_t& dqopqop, jac_matrix_t& new_J) {
    getter::element(new_J, 0u, 0u) =
        getter::element(J_transport, 0u, 0u) +
        getter::element(J_transport, 4u, 0u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 0u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 0u) =
        getter::element(J_transport, 1u, 0u) +
        getter::element(J_transport, 4u, 0u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 0u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 0u) =
        getter::element(J_transport, 2u, 0u) +
        getter::element(J_transport, 4u, 0u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 0u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 0u) = getter::element(J_transport, 3u, 0u);
    getter::element(new_J, 4u, 0u) =
        getter::element(J_transport, 4u, 0u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 0u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 0u) =
        getter::element(J_transport, 4u, 0u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 0u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 0u) =
        getter::element(J_transport, 4u, 0u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 0u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 0u) =
        dqopqop * getter::element(J_transport, 7u, 0u);
    getter::element(new_J, 0u, 1u) =
        getter::element(J_transport, 0u, 1u) +
        getter::element(J_transport, 4u, 1u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 1u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 1u) =
        getter::element(J_transport, 1u, 1u) +
        getter::element(J_transport, 4u, 1u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 1u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 1u) =
        getter::element(J_transport, 2u, 1u) +
        getter::element(J_transport, 4u, 1u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 1u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 1u) = getter::element(J_transport, 3u, 1u);
    getter::element(new_J, 4u, 1u) =
        getter::element(J_transport, 4u, 1u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 1u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 1u) =
        getter::element(J_transport, 4u, 1u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 1u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 1u) =
        getter::element(J_transport, 4u, 1u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 1u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 1u) =
        dqopqop * getter::element(J_transport, 7u, 1u);
    getter::element(new_J, 0u, 2u) =
        getter::element(J_transport, 0u, 2u) +
        getter::element(J_transport, 4u, 2u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 2u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 2u) =
        getter::element(J_transport, 1u, 2u) +
        getter::element(J_transport, 4u, 2u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 2u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 2u) =
        getter::element(J_transport, 2u, 2u) +
        getter::element(J_transport, 4u, 2u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 2u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 2u) = getter::element(J_transport, 3u, 2u);
    getter::element(new_J, 4u, 2u) =
        getter::element(J_transport, 4u, 2u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 2u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 2u) =
        getter::element(J_transport, 4u, 2u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 2u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 2u) =
        getter::element(J_transport, 4u, 2u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 2u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 2u) =
        dqopqop * getter::element(J_transport, 7u, 2u);
    getter::element(new_J, 0u, 3u) =
        getter::element(J_transport, 0u, 3u) +
        getter::element(J_transport, 4u, 3u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 3u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 3u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 3u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 3u) =
        getter::element(J_transport, 1u, 3u) +
        getter::element(J_transport, 4u, 3u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 3u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 3u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 3u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 3u) =
        getter::element(J_transport, 2u, 3u) +
        getter::element(J_transport, 4u, 3u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 3u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 3u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 3u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 3u) = getter::element(J_transport, 3u, 3u);
    getter::element(new_J, 4u, 3u) =
        getter::element(J_transport, 4u, 3u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 3u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 3u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 3u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 3u) =
        getter::element(J_transport, 4u, 3u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 3u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 3u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 3u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 3u) =
        getter::element(J_transport, 4u, 3u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 3u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 3u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 3u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 3u) =
        dqopqop * getter::element(J_transport, 7u, 3u);
    getter::element(new_J, 0u, 4u) =
        getter::element(J_transport, 0u, 4u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 4u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 4u) =
        getter::element(J_transport, 1u, 4u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 4u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 4u) =
        getter::element(J_transport, 2u, 4u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 4u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 4u) = getter::element(J_transport, 3u, 4u);
    getter::element(new_J, 4u, 4u) =
        getter::element(J_transport, 4u, 4u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 4u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 4u) =
        getter::element(J_transport, 4u, 4u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 4u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 4u) =
        getter::element(J_transport, 4u, 4u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 4u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 4u) =
        dqopqop * getter::element(J_transport, 7u, 4u);
    getter::element(new_J, 0u, 5u) =
        getter::element(J_transport, 0u, 5u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 5u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 5u) =
        getter::element(J_transport, 1u, 5u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 5u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 5u) =
        getter::element(J_transport, 2u, 5u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 5u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 5u) = getter::element(J_transport, 3u, 5u);
    getter::element(new_J, 4u, 5u) =
        getter::element(J_transport, 4u, 5u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 5u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 5u) =
        getter::element(J_transport, 4u, 5u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 5u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 5u) =
        getter::element(J_transport, 4u, 5u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 5u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 5u) =
        dqopqop * getter::element(J_transport, 7u, 5u);
    getter::element(new_J, 0u, 6u) =
        getter::element(J_transport, 0u, 6u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 6u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 6u) =
        getter::element(J_transport, 1u, 6u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 6u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 6u) =
        getter::element(J_transport, 2u, 6u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 6u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 6u) = getter::element(J_transport, 3u, 6u);
    getter::element(new_J, 4u, 6u) =
        getter::element(J_transport, 4u, 6u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 6u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 6u) =
        getter::element(J_transport, 4u, 6u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 6u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 6u) =
        getter::element(J_transport, 4u, 6u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 6u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 6u) =
        dqopqop * getter::element(J_transport, 7u, 6u);
    getter::element(new_J, 0u, 7u) =
        getter::element(J_transport, 0u, 7u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 7u) =
        getter::element(J_transport, 1u, 7u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 7u) =
        getter::element(J_transport, 2u, 7u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 7u) = getter::element(J_transport, 3u, 7u);
    getter::element(new_J, 4u, 7u) =
        getter::element(J_transport, 4u, 7u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 7u) =
        getter::element(J_transport, 4u, 7u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 7u) =
        getter::element(J_transport, 4u, 7u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 7u) =
        dqopqop * getter::element(J_transport, 7u, 7u);
}
template <typename jac_matrix_t, typename matrix33_t, typename matrix31_t,
          typename scalar_t>
DETRAY_HOST_DEVICE void inline update_transport_jacobian_with_gradient_impl(
    const jac_matrix_t& J_transport, const matrix33_t& dFdt,
    const matrix33_t& dGdt, const matrix33_t& dFdr, const matrix33_t& dGdr,
    const matrix31_t& dFdqop, const matrix31_t& dGdqop, const scalar_t& dqopqop,
    jac_matrix_t& new_J) {
    getter::element(new_J, 0u, 0u) =
        getter::element(J_transport, 0u, 0u) * getter::element(dFdr, 0u, 0u) +
        getter::element(J_transport, 1u, 0u) * getter::element(dFdr, 0u, 1u) +
        getter::element(J_transport, 2u, 0u) * getter::element(dFdr, 0u, 2u) +
        getter::element(J_transport, 4u, 0u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 0u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 0u) =
        getter::element(J_transport, 0u, 0u) * getter::element(dFdr, 1u, 0u) +
        getter::element(J_transport, 1u, 0u) * getter::element(dFdr, 1u, 1u) +
        getter::element(J_transport, 2u, 0u) * getter::element(dFdr, 1u, 2u) +
        getter::element(J_transport, 4u, 0u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 0u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 0u) =
        getter::element(J_transport, 0u, 0u) * getter::element(dFdr, 2u, 0u) +
        getter::element(J_transport, 1u, 0u) * getter::element(dFdr, 2u, 1u) +
        getter::element(J_transport, 2u, 0u) * getter::element(dFdr, 2u, 2u) +
        getter::element(J_transport, 4u, 0u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 0u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 0u) = getter::element(J_transport, 3u, 0u);
    getter::element(new_J, 4u, 0u) =
        getter::element(J_transport, 0u, 0u) * getter::element(dGdr, 0u, 0u) +
        getter::element(J_transport, 1u, 0u) * getter::element(dGdr, 0u, 1u) +
        getter::element(J_transport, 2u, 0u) * getter::element(dGdr, 0u, 2u) +
        getter::element(J_transport, 4u, 0u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 0u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 0u) =
        getter::element(J_transport, 0u, 0u) * getter::element(dGdr, 1u, 0u) +
        getter::element(J_transport, 1u, 0u) * getter::element(dGdr, 1u, 1u) +
        getter::element(J_transport, 2u, 0u) * getter::element(dGdr, 1u, 2u) +
        getter::element(J_transport, 4u, 0u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 0u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 0u) =
        getter::element(J_transport, 0u, 0u) * getter::element(dGdr, 2u, 0u) +
        getter::element(J_transport, 1u, 0u) * getter::element(dGdr, 2u, 1u) +
        getter::element(J_transport, 2u, 0u) * getter::element(dGdr, 2u, 2u) +
        getter::element(J_transport, 4u, 0u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 0u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 0u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 0u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 0u) =
        dqopqop * getter::element(J_transport, 7u, 0u);
    getter::element(new_J, 0u, 1u) =
        getter::element(J_transport, 0u, 1u) * getter::element(dFdr, 0u, 0u) +
        getter::element(J_transport, 1u, 1u) * getter::element(dFdr, 0u, 1u) +
        getter::element(J_transport, 2u, 1u) * getter::element(dFdr, 0u, 2u) +
        getter::element(J_transport, 4u, 1u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 1u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 1u) =
        getter::element(J_transport, 0u, 1u) * getter::element(dFdr, 1u, 0u) +
        getter::element(J_transport, 1u, 1u) * getter::element(dFdr, 1u, 1u) +
        getter::element(J_transport, 2u, 1u) * getter::element(dFdr, 1u, 2u) +
        getter::element(J_transport, 4u, 1u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 1u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 1u) =
        getter::element(J_transport, 0u, 1u) * getter::element(dFdr, 2u, 0u) +
        getter::element(J_transport, 1u, 1u) * getter::element(dFdr, 2u, 1u) +
        getter::element(J_transport, 2u, 1u) * getter::element(dFdr, 2u, 2u) +
        getter::element(J_transport, 4u, 1u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 1u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 1u) = getter::element(J_transport, 3u, 1u);
    getter::element(new_J, 4u, 1u) =
        getter::element(J_transport, 0u, 1u) * getter::element(dGdr, 0u, 0u) +
        getter::element(J_transport, 1u, 1u) * getter::element(dGdr, 0u, 1u) +
        getter::element(J_transport, 2u, 1u) * getter::element(dGdr, 0u, 2u) +
        getter::element(J_transport, 4u, 1u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 1u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 1u) =
        getter::element(J_transport, 0u, 1u) * getter::element(dGdr, 1u, 0u) +
        getter::element(J_transport, 1u, 1u) * getter::element(dGdr, 1u, 1u) +
        getter::element(J_transport, 2u, 1u) * getter::element(dGdr, 1u, 2u) +
        getter::element(J_transport, 4u, 1u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 1u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 1u) =
        getter::element(J_transport, 0u, 1u) * getter::element(dGdr, 2u, 0u) +
        getter::element(J_transport, 1u, 1u) * getter::element(dGdr, 2u, 1u) +
        getter::element(J_transport, 2u, 1u) * getter::element(dGdr, 2u, 2u) +
        getter::element(J_transport, 4u, 1u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 1u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 1u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 1u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 1u) =
        dqopqop * getter::element(J_transport, 7u, 1u);
    getter::element(new_J, 0u, 2u) =
        getter::element(J_transport, 0u, 2u) * getter::element(dFdr, 0u, 0u) +
        getter::element(J_transport, 1u, 2u) * getter::element(dFdr, 0u, 1u) +
        getter::element(J_transport, 2u, 2u) * getter::element(dFdr, 0u, 2u) +
        getter::element(J_transport, 4u, 2u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 2u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 2u) =
        getter::element(J_transport, 0u, 2u) * getter::element(dFdr, 1u, 0u) +
        getter::element(J_transport, 1u, 2u) * getter::element(dFdr, 1u, 1u) +
        getter::element(J_transport, 2u, 2u) * getter::element(dFdr, 1u, 2u) +
        getter::element(J_transport, 4u, 2u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 2u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 2u) =
        getter::element(J_transport, 0u, 2u) * getter::element(dFdr, 2u, 0u) +
        getter::element(J_transport, 1u, 2u) * getter::element(dFdr, 2u, 1u) +
        getter::element(J_transport, 2u, 2u) * getter::element(dFdr, 2u, 2u) +
        getter::element(J_transport, 4u, 2u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 2u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 2u) = getter::element(J_transport, 3u, 2u);
    getter::element(new_J, 4u, 2u) =
        getter::element(J_transport, 0u, 2u) * getter::element(dGdr, 0u, 0u) +
        getter::element(J_transport, 1u, 2u) * getter::element(dGdr, 0u, 1u) +
        getter::element(J_transport, 2u, 2u) * getter::element(dGdr, 0u, 2u) +
        getter::element(J_transport, 4u, 2u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 2u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 2u) =
        getter::element(J_transport, 0u, 2u) * getter::element(dGdr, 1u, 0u) +
        getter::element(J_transport, 1u, 2u) * getter::element(dGdr, 1u, 1u) +
        getter::element(J_transport, 2u, 2u) * getter::element(dGdr, 1u, 2u) +
        getter::element(J_transport, 4u, 2u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 2u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 2u) =
        getter::element(J_transport, 0u, 2u) * getter::element(dGdr, 2u, 0u) +
        getter::element(J_transport, 1u, 2u) * getter::element(dGdr, 2u, 1u) +
        getter::element(J_transport, 2u, 2u) * getter::element(dGdr, 2u, 2u) +
        getter::element(J_transport, 4u, 2u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 2u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 2u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 2u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 2u) =
        dqopqop * getter::element(J_transport, 7u, 2u);
    getter::element(new_J, 0u, 3u) =
        getter::element(J_transport, 0u, 3u) * getter::element(dFdr, 0u, 0u) +
        getter::element(J_transport, 1u, 3u) * getter::element(dFdr, 0u, 1u) +
        getter::element(J_transport, 2u, 3u) * getter::element(dFdr, 0u, 2u) +
        getter::element(J_transport, 4u, 3u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 3u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 3u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 3u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 3u) =
        getter::element(J_transport, 0u, 3u) * getter::element(dFdr, 1u, 0u) +
        getter::element(J_transport, 1u, 3u) * getter::element(dFdr, 1u, 1u) +
        getter::element(J_transport, 2u, 3u) * getter::element(dFdr, 1u, 2u) +
        getter::element(J_transport, 4u, 3u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 3u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 3u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 3u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 3u) =
        getter::element(J_transport, 0u, 3u) * getter::element(dFdr, 2u, 0u) +
        getter::element(J_transport, 1u, 3u) * getter::element(dFdr, 2u, 1u) +
        getter::element(J_transport, 2u, 3u) * getter::element(dFdr, 2u, 2u) +
        getter::element(J_transport, 4u, 3u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 3u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 3u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 3u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 3u) = getter::element(J_transport, 3u, 3u);
    getter::element(new_J, 4u, 3u) =
        getter::element(J_transport, 0u, 3u) * getter::element(dGdr, 0u, 0u) +
        getter::element(J_transport, 1u, 3u) * getter::element(dGdr, 0u, 1u) +
        getter::element(J_transport, 2u, 3u) * getter::element(dGdr, 0u, 2u) +
        getter::element(J_transport, 4u, 3u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 3u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 3u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 3u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 3u) =
        getter::element(J_transport, 0u, 3u) * getter::element(dGdr, 1u, 0u) +
        getter::element(J_transport, 1u, 3u) * getter::element(dGdr, 1u, 1u) +
        getter::element(J_transport, 2u, 3u) * getter::element(dGdr, 1u, 2u) +
        getter::element(J_transport, 4u, 3u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 3u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 3u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 3u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 3u) =
        getter::element(J_transport, 0u, 3u) * getter::element(dGdr, 2u, 0u) +
        getter::element(J_transport, 1u, 3u) * getter::element(dGdr, 2u, 1u) +
        getter::element(J_transport, 2u, 3u) * getter::element(dGdr, 2u, 2u) +
        getter::element(J_transport, 4u, 3u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 3u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 3u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 3u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 3u) =
        dqopqop * getter::element(J_transport, 7u, 3u);
    getter::element(new_J, 0u, 4u) =
        getter::element(J_transport, 0u, 4u) * getter::element(dFdr, 0u, 0u) +
        getter::element(J_transport, 1u, 4u) * getter::element(dFdr, 0u, 1u) +
        getter::element(J_transport, 2u, 4u) * getter::element(dFdr, 0u, 2u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 4u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 4u) =
        getter::element(J_transport, 0u, 4u) * getter::element(dFdr, 1u, 0u) +
        getter::element(J_transport, 1u, 4u) * getter::element(dFdr, 1u, 1u) +
        getter::element(J_transport, 2u, 4u) * getter::element(dFdr, 1u, 2u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 4u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 4u) =
        getter::element(J_transport, 0u, 4u) * getter::element(dFdr, 2u, 0u) +
        getter::element(J_transport, 1u, 4u) * getter::element(dFdr, 2u, 1u) +
        getter::element(J_transport, 2u, 4u) * getter::element(dFdr, 2u, 2u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 4u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 4u) = getter::element(J_transport, 3u, 4u);
    getter::element(new_J, 4u, 4u) =
        getter::element(J_transport, 0u, 4u) * getter::element(dGdr, 0u, 0u) +
        getter::element(J_transport, 1u, 4u) * getter::element(dGdr, 0u, 1u) +
        getter::element(J_transport, 2u, 4u) * getter::element(dGdr, 0u, 2u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 4u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 4u) =
        getter::element(J_transport, 0u, 4u) * getter::element(dGdr, 1u, 0u) +
        getter::element(J_transport, 1u, 4u) * getter::element(dGdr, 1u, 1u) +
        getter::element(J_transport, 2u, 4u) * getter::element(dGdr, 1u, 2u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 4u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 4u) =
        getter::element(J_transport, 0u, 4u) * getter::element(dGdr, 2u, 0u) +
        getter::element(J_transport, 1u, 4u) * getter::element(dGdr, 2u, 1u) +
        getter::element(J_transport, 2u, 4u) * getter::element(dGdr, 2u, 2u) +
        getter::element(J_transport, 4u, 4u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 4u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 4u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 4u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 4u) =
        dqopqop * getter::element(J_transport, 7u, 4u);
    getter::element(new_J, 0u, 5u) =
        getter::element(J_transport, 0u, 5u) * getter::element(dFdr, 0u, 0u) +
        getter::element(J_transport, 1u, 5u) * getter::element(dFdr, 0u, 1u) +
        getter::element(J_transport, 2u, 5u) * getter::element(dFdr, 0u, 2u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 5u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 5u) =
        getter::element(J_transport, 0u, 5u) * getter::element(dFdr, 1u, 0u) +
        getter::element(J_transport, 1u, 5u) * getter::element(dFdr, 1u, 1u) +
        getter::element(J_transport, 2u, 5u) * getter::element(dFdr, 1u, 2u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 5u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 5u) =
        getter::element(J_transport, 0u, 5u) * getter::element(dFdr, 2u, 0u) +
        getter::element(J_transport, 1u, 5u) * getter::element(dFdr, 2u, 1u) +
        getter::element(J_transport, 2u, 5u) * getter::element(dFdr, 2u, 2u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 5u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 5u) = getter::element(J_transport, 3u, 5u);
    getter::element(new_J, 4u, 5u) =
        getter::element(J_transport, 0u, 5u) * getter::element(dGdr, 0u, 0u) +
        getter::element(J_transport, 1u, 5u) * getter::element(dGdr, 0u, 1u) +
        getter::element(J_transport, 2u, 5u) * getter::element(dGdr, 0u, 2u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 5u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 5u) =
        getter::element(J_transport, 0u, 5u) * getter::element(dGdr, 1u, 0u) +
        getter::element(J_transport, 1u, 5u) * getter::element(dGdr, 1u, 1u) +
        getter::element(J_transport, 2u, 5u) * getter::element(dGdr, 1u, 2u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 5u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 5u) =
        getter::element(J_transport, 0u, 5u) * getter::element(dGdr, 2u, 0u) +
        getter::element(J_transport, 1u, 5u) * getter::element(dGdr, 2u, 1u) +
        getter::element(J_transport, 2u, 5u) * getter::element(dGdr, 2u, 2u) +
        getter::element(J_transport, 4u, 5u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 5u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 5u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 5u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 5u) =
        dqopqop * getter::element(J_transport, 7u, 5u);
    getter::element(new_J, 0u, 6u) =
        getter::element(J_transport, 0u, 6u) * getter::element(dFdr, 0u, 0u) +
        getter::element(J_transport, 1u, 6u) * getter::element(dFdr, 0u, 1u) +
        getter::element(J_transport, 2u, 6u) * getter::element(dFdr, 0u, 2u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 6u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 6u) =
        getter::element(J_transport, 0u, 6u) * getter::element(dFdr, 1u, 0u) +
        getter::element(J_transport, 1u, 6u) * getter::element(dFdr, 1u, 1u) +
        getter::element(J_transport, 2u, 6u) * getter::element(dFdr, 1u, 2u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 6u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 6u) =
        getter::element(J_transport, 0u, 6u) * getter::element(dFdr, 2u, 0u) +
        getter::element(J_transport, 1u, 6u) * getter::element(dFdr, 2u, 1u) +
        getter::element(J_transport, 2u, 6u) * getter::element(dFdr, 2u, 2u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 6u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 6u) = getter::element(J_transport, 3u, 6u);
    getter::element(new_J, 4u, 6u) =
        getter::element(J_transport, 0u, 6u) * getter::element(dGdr, 0u, 0u) +
        getter::element(J_transport, 1u, 6u) * getter::element(dGdr, 0u, 1u) +
        getter::element(J_transport, 2u, 6u) * getter::element(dGdr, 0u, 2u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 6u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 6u) =
        getter::element(J_transport, 0u, 6u) * getter::element(dGdr, 1u, 0u) +
        getter::element(J_transport, 1u, 6u) * getter::element(dGdr, 1u, 1u) +
        getter::element(J_transport, 2u, 6u) * getter::element(dGdr, 1u, 2u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 6u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 6u) =
        getter::element(J_transport, 0u, 6u) * getter::element(dGdr, 2u, 0u) +
        getter::element(J_transport, 1u, 6u) * getter::element(dGdr, 2u, 1u) +
        getter::element(J_transport, 2u, 6u) * getter::element(dGdr, 2u, 2u) +
        getter::element(J_transport, 4u, 6u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 6u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 6u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 6u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 6u) =
        dqopqop * getter::element(J_transport, 7u, 6u);
    getter::element(new_J, 0u, 7u) =
        getter::element(J_transport, 0u, 7u) * getter::element(dFdr, 0u, 0u) +
        getter::element(J_transport, 1u, 7u) * getter::element(dFdr, 0u, 1u) +
        getter::element(J_transport, 2u, 7u) * getter::element(dFdr, 0u, 2u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dFdt, 0u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dFdt, 0u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dFdt, 0u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dFdqop, 0u);
    getter::element(new_J, 1u, 7u) =
        getter::element(J_transport, 0u, 7u) * getter::element(dFdr, 1u, 0u) +
        getter::element(J_transport, 1u, 7u) * getter::element(dFdr, 1u, 1u) +
        getter::element(J_transport, 2u, 7u) * getter::element(dFdr, 1u, 2u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dFdt, 1u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dFdt, 1u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dFdt, 1u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dFdqop, 1u);
    getter::element(new_J, 2u, 7u) =
        getter::element(J_transport, 0u, 7u) * getter::element(dFdr, 2u, 0u) +
        getter::element(J_transport, 1u, 7u) * getter::element(dFdr, 2u, 1u) +
        getter::element(J_transport, 2u, 7u) * getter::element(dFdr, 2u, 2u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dFdt, 2u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dFdt, 2u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dFdt, 2u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dFdqop, 2u);
    getter::element(new_J, 3u, 7u) = getter::element(J_transport, 3u, 7u);
    getter::element(new_J, 4u, 7u) =
        getter::element(J_transport, 0u, 7u) * getter::element(dGdr, 0u, 0u) +
        getter::element(J_transport, 1u, 7u) * getter::element(dGdr, 0u, 1u) +
        getter::element(J_transport, 2u, 7u) * getter::element(dGdr, 0u, 2u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dGdt, 0u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dGdt, 0u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dGdt, 0u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dGdqop, 0u);
    getter::element(new_J, 5u, 7u) =
        getter::element(J_transport, 0u, 7u) * getter::element(dGdr, 1u, 0u) +
        getter::element(J_transport, 1u, 7u) * getter::element(dGdr, 1u, 1u) +
        getter::element(J_transport, 2u, 7u) * getter::element(dGdr, 1u, 2u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dGdt, 1u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dGdt, 1u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dGdt, 1u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dGdqop, 1u);
    getter::element(new_J, 6u, 7u) =
        getter::element(J_transport, 0u, 7u) * getter::element(dGdr, 2u, 0u) +
        getter::element(J_transport, 1u, 7u) * getter::element(dGdr, 2u, 1u) +
        getter::element(J_transport, 2u, 7u) * getter::element(dGdr, 2u, 2u) +
        getter::element(J_transport, 4u, 7u) * getter::element(dGdt, 2u, 0u) +
        getter::element(J_transport, 5u, 7u) * getter::element(dGdt, 2u, 1u) +
        getter::element(J_transport, 6u, 7u) * getter::element(dGdt, 2u, 2u) +
        getter::element(J_transport, 7u, 7u) * getter::element(dGdqop, 2u);
    getter::element(new_J, 7u, 7u) =
        dqopqop * getter::element(J_transport, 7u, 7u);
}
}  // namespace detray::detail
